name: Continuous Deployment to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7' 
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get
        # Thinking to check outdated too

      - name: Run Tests
        run: flutter test

  android:
    name: Build and Deploy Android
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7' 
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build Android
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-dev.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios:
    name: Build and Deploy iOS
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7' 
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --debug --no-codesign

      - name: Upload iOS
        uses: actions/upload-artifact@v2
        with:
          name: ios-app
          path: |
            build/ios/ipa/Runner.app
            build/ios/iphones/Runner.app
